import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

import { preview } from "../assets";
import { getRandomPrompt } from "../utils";
import { FormField, Loader } from "../components";

const CreatePost = () => {
    const navigate = useNavigate();

    const [form, setForm] = useState({
        name: "",
        prompt: "",
        photo: "",
    });

    const [generatingImg, setGeneratingImg] = useState(false);
    const [loading, setLoading] = useState(false);

    const handleChange = (e) => {
        setForm({ ...form, [e.target.name]: e.target.value });
    };

    const handleSurpriseMe = () => {
        const randomPrompt = getRandomPrompt(form.prompt);
        setForm({ ...form, prompt: randomPrompt });
    };

    const generateImage = async () => {
        if (form.prompt) {
            try {
                setGeneratingImg(true);
                const response = await fetch(
                    "http://localhost:8080/api/v1/dalle",
                    {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json",
                        },
                        body: JSON.stringify({
                            prompt: form.prompt,
                        }),
                    }
                );

                const data = await response.json();

                setForm({
                    ...form,
                    photo: `data:image/jpeg;base64,${data.photo}`,
                });
            } catch (err) {
                alert(err);
            } finally {
                setGeneratingImg(false);
            }
        } else {
            alert("Please provide proper prompt");
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        if (form.prompt && form.photo) {
            setLoading(true);
            try {
                const response = await fetch(
                    "http://localhost:8080/api/v1/post",
                    {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json",
                        },
                        body: JSON.stringify({ ...form }),
                    }
                );

                await response.json();
                alert("Success");
                navigate("/");
            } catch (err) {
                alert(err);
            } finally {
                setLoading(false);
            }
        } else {
            alert("Plase enter a prompt and generate an image");
        }
    };

    return (
        <section className="max-w-7xl mx-auto flex flex-col items-center">
            <div className="block px-72 py-16 pb-32 bg-white border border-white rounded-lg shadow dark:bg-[#141516] dark:border-gray-700 ">
                <div>
                    <h1 className="text-7xl font-extrabold text-transparent bg-clip-text bg-gradient-to-b from-gray-50 to-white-50 text-center">
                        Create
                    </h1>
                    <p className="mt-6 text-[#666e75] text-[14px] text-center">
                        Create through a collection of imaginative and visually
                        stunning images generated by DALL-E AI and share them on
                        the website
                    </p>
                </div>

                <form className="mt-16 max-w-3xl" onSubmit={handleSubmit}>
                    <div className="flex flex-row gap-10">
                        <div className="flex flex-col gap-10 w-96">
                            <FormField
                                labelName="Your Name"
                                type="text"
                                name="name"
                                placeholder="Ex., john doe"
                                value={form.name}
                                handleChange={handleChange}
                            />

                            <FormField
                                labelName="Prompt"
                                type="text"
                                name="prompt"
                                placeholder="an armchair in the shape of an avocado"
                                value={form.prompt}
                                handleChange={handleChange}
                                isSurpriseMe
                                handleSurpriseMe={handleSurpriseMe}
                            />
                            <div className="mt-5 flex flex-col gap-5">
                                <button
                                    type="button"
                                    onClick={generateImage}
                                    className=" text-green-700 hover:text-white border border-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center  dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-600 dark:focus:ring-green-800"
                                >
                                    {generatingImg
                                        ? "Generating..."
                                        : "Generate"}
                                </button>
                                <button
                                    type="submit"
                                    className="text-purple-700 hover:text-white border border-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:border-purple-400 dark:text-purple-400 dark:hover:text-white dark:hover:bg-purple-500 dark:focus:ring-purple-900"
                                >
                                    {loading
                                        ? "Sharing..."
                                        : "Share on website"}
                                </button>
                            </div>
                        </div>

                        <div className="flex flex-col">
                            <div className="relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-96 p-3 h-96 flex justify-center items-center">
                                {form.photo ? (
                                    <img
                                        src={form.photo}
                                        alt={form.prompt}
                                        className="w-full h-full object-contain filter-none"
                                    />
                                ) : (
                                    <img
                                        src={preview}
                                        alt="preview"
                                        className="w-9/12 h-9/12 object-contain opacity-40 filter-none"
                                    />
                                )}

                                {generatingImg && (
                                    <div className="absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg">
                                        <Loader />
                                    </div>
                                )}
                            </div>
                            <p className="mt-2 text-[#666e75] text-[14px] text-center max-w-[380px]">
                                ** Once you have created an image, you can share
                                it with others on this website
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </section>
    );
};

export default CreatePost;
