import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

import { preview } from "../assets";
import { getRandomPrompt } from "../utils";
import { FormField, Loader } from "../components";

/**
 * CreatePost component for generating and sharing AI-generated images
 * @returns {JSX.Element} A form section for creating and sharing AI-generated images
 */
const CreatePost = () => {
    const navigate = useNavigate();

    const [form, setForm] = useState({
        name: "",
        prompt: "",
        photo: "",
    });

    const [generatingImg, setGeneratingImg] = useState(false);
    const [loading, setLoading] = useState(false);

    const handleChange = (e) =>
        setForm({ ...form, [e.target.name]: e.target.value });

    const handleSurpriseMe = () => {
        const randomPrompt = getRandomPrompt(form.prompt);
        setForm({ ...form, prompt: randomPrompt });
    };

    const generateImage = async () => {
        if (form.prompt) {
            try {
                setGeneratingImg(true);
                const response = await fetch(
                    "https://main-do40.onrender.com/api/v1/dalle",
                    {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json",
                        },
                        body: JSON.stringify({
                            prompt: form.prompt,
                        }),
                    }
                );

                const data = await response.json();

                setForm({
                    ...form,
                    photo: `data:image/jpeg;base64,${data.photo}`,
                });
            } catch (err) {
                alert(err);
            } finally {
                setGeneratingImg(false);
            }
        } else {
            alert("Please provide proper prompt");
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        if (form.prompt && form.photo) {
            setLoading(true);
            try {
                const response = await fetch(
                    "https://main-do40.onrender.com/api/v1/post",
                    {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json",
                        },
                        body: JSON.stringify({ ...form }),
                    }
                );

                await response.json();
                alert("Success");
                navigate("/");
            } catch (err) {
                alert(err);
            } finally {
                setLoading(false);
            }
        } else {
            alert("Plase enter a prompt and generate an image");
        }
    };

    return (
        <section className="max-w-7xl mx-auto flex flex-col items-center">
            <div className="flex flex-col items-center overflow-hidden 2xl:px-72 sm:px-20 px-3 ease-in duration-100 pt-16 sm:pb-28 pb-3 bg-white border border-white rounded-lg shadow dark:bg-[#141516] dark:border-gray-700 drop-in">
                <div className="drop-in">
                    <h1 className="sm:text-7xl text-5xl font-extrabold animate-text bg-gradient-to-r from-purple-500 via-pink-500 to-orange-500 bg-clip-text text-transparent text-center">
                        Create
                    </h1>
                    <p className="mt-6 text-[#666e75] text-[14px] text-center">
                        Create through a collection of images generated by
                        DALL-E AI and share them on the website. Just enter your
                        name, prompt or use one of the many pre-determined
                        prompts with the "Surprise me" button and generate your
                        image.green
                    </p>
                </div>

                <form
                    className="mt-16 max-w-3xl drop-in-2 items-center"
                    onSubmit={handleSubmit}
                >
                    <div className="flex lg:flex-row flex-col gap-10 items-center sm:items-start">
                        <div className="flex flex-col gap-10 sm:w-96 w-72 ">
                            <FormField
                                labelName="Your Name"
                                type="text"
                                name="name"
                                placeholder="Ex., john doe"
                                value={form.name}
                                handleChange={handleChange}
                            />

                            <FormField
                                labelName="Prompt"
                                type="text"
                                name="prompt"
                                placeholder="an armchair in the shape of an avocado"
                                value={form.prompt}
                                handleChange={handleChange}
                                isSurpriseMe
                                handleSurpriseMe={handleSurpriseMe}
                            />
                            <div className="mt-5 flex flex-col gap-5">
                                <button
                                    type="button"
                                    onClick={generateImage}
                                    class="relative inline-flex items-center justify-center p-0.5 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br  from-purple-500  via-pink-500 to-orange-400 group-hover:from-purple-500 group-hover:via-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800 animate-text"
                                >
                                    <span class="relative px-36 max-md:px-28 min-[640px]:px-40 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0 animate-text">
                                        {generatingImg
                                            ? "Generating..."
                                            : "Generate"}
                                    </span>
                                </button>
                                <button
                                    type="submit"
                                    className="text-purple-700 hover:text-white border border-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:border-purple-400 dark:text-purple-400 dark:hover:text-white dark:hover:bg-purple-500 dark:focus:ring-purple-900"
                                >
                                    {loading
                                        ? "Sharing..."
                                        : "Share on website"}
                                </button>
                            </div>
                        </div>

                        <div className="flex flex-col">
                            <div className="relative border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-700 focus:border-purple-800 sm:w-96 p-3 sm:h-96 flex justify-center items-center dark:bg-[#141516] dark:border-gray-500 dark:placeholder-gray-400 dark:text-white">
                                {form.photo ? (
                                    <img
                                        src={form.photo}
                                        alt={form.prompt}
                                        className="w-full h-full object-contain"
                                    />
                                ) : (
                                    <img
                                        src={preview}
                                        alt="preview"
                                        className="w-9/12 h-9/12 object-contain opacity-90"
                                    />
                                )}

                                {generatingImg && (
                                    <div className="absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg">
                                        <Loader />
                                    </div>
                                )}
                            </div>
                            <p className="mt-2 text-[#666e75] text-[14px] text-center max-w-[380px]">
                                ** Once you have created an image, you can share
                                it with others on this website
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </section>
    );
};

export default CreatePost;
